version: "3.7"

services:
  emabobeat-detector:
    container_name: emobeat-detector
    image: haphuthinh/emobeat-detector:release-cd9163f6f7cf43917a2cdc0601af84d582892737
    ports:
      - "5099:5000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 812M