version: "3.7"

services:
  emabobeat-recommend:
    image: haphuthinh/emobeat-detector:release-ce2da672cea1b77fe6fc318a09b26433a7dbff95
    ports:
      - "5099:5000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M