version: '3.9'

services:
  emobeat-media-service:
    container_name: emobeat-media-service
    build:
      context: .
    restart: unless-stopped
    ports:
      - '8580:4000'
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 512M
